seed: 42

# data paths
raw_data_path: /workspaces/ChatbotWiz/data/raw/dataset.txt
first_message_path: /workspaces/ChatbotWiz/data/processed/first_message.csv
first_message_topic_path: /workspaces/ChatbotWiz/data/processed/first_message_topic.csv


# model paths
models_folder: /workspaces/ChatbotWiz/models/
clf_base: clf_base.joblib
clf_HP_search: clf_HP_search.joblib


# parsing config
encoding: cp865

# predict 
score_metric: accuracy
parameters: 
  vect__ngram_range: 
  - - 1
    - 1
  - - 1
    - 2
  vect__stop_words: 
  - null
  - english
  clf__alpha: 
  - 1
  - 0.1
  - 0.01
  clf__max_iter: 
  - 1
  - 2
  - 5


# To remove outputs folder created by hydra
defaults:  
  - _self_  
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled  
  
hydra:  
  output_subdir: null  
  run:  
    dir: .